// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3yHl81HLtI7aU1hUi8OpUv6HHKavc3k0',
    appId: '1:593092556470:web:7845299fbee960a3a7d817',
    messagingSenderId: '593092556470',
    projectId: 'ble-attendance-system-cfc25',
    authDomain: 'ble-attendance-system-cfc25.firebaseapp.com',
    storageBucket: 'ble-attendance-system-cfc25.firebasestorage.app',
    measurementId: 'G-4FLEY2W1H3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDkMk01IAkqwo6kMwyog-7xkWNZWFYSEc',
    appId: '1:593092556470:android:bf71919bc17795d2a7d817',
    messagingSenderId: '593092556470',
    projectId: 'ble-attendance-system-cfc25',
    storageBucket: 'ble-attendance-system-cfc25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCZRa-p23bVu5ZmNxOMXbJY4S0sj3lCbk',
    appId: '1:593092556470:ios:abe9f5a0e30a8861a7d817',
    messagingSenderId: '593092556470',
    projectId: 'ble-attendance-system-cfc25',
    storageBucket: 'ble-attendance-system-cfc25.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCZRa-p23bVu5ZmNxOMXbJY4S0sj3lCbk',
    appId: '1:593092556470:ios:abe9f5a0e30a8861a7d817',
    messagingSenderId: '593092556470',
    projectId: 'ble-attendance-system-cfc25',
    storageBucket: 'ble-attendance-system-cfc25.firebasestorage.app',
    iosBundleId: 'com.example.attendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3yHl81HLtI7aU1hUi8OpUv6HHKavc3k0',
    appId: '1:593092556470:web:5be1033b2a4f1fa7a7d817',
    messagingSenderId: '593092556470',
    projectId: 'ble-attendance-system-cfc25',
    authDomain: 'ble-attendance-system-cfc25.firebaseapp.com',
    storageBucket: 'ble-attendance-system-cfc25.firebasestorage.app',
    measurementId: 'G-BWHYJT39KQ',
  );
}
